package org.tedros.tools.module.ai.function;

import java.util.Map;

import org.slf4j.Logger;
import org.tedros.ai.TFunctionHelper;
import org.tedros.ai.function.TFunction;
import org.tedros.ai.function.model.ViewPath;
import org.tedros.ai.openai.model.ToolCallResult;
import org.tedros.ai.web.TerosWebViewBridge;
import org.tedros.api.form.ITFieldBox;
import org.tedros.api.form.ITModelForm;
import org.tedros.api.presenter.view.ITView;
import org.tedros.core.context.TViewDescriptor;
import org.tedros.core.context.TedrosAppManager;
import org.tedros.fx.presenter.dynamic.TDynaPresenter;
import org.tedros.fx.presenter.model.behavior.TViewBehavior;
import org.tedros.tools.module.ai.model.HtmlMessageViewerMV;
import org.tedros.tools.module.ai.model.HtmlMessageViewerModel;
import org.tedros.util.TLoggerUtil;

import javafx.application.Platform;
import javafx.scene.web.WebView;

public class ShowHtmlAiResponse extends TFunction<HtmlContent> {
	
	private static final Logger LOGGER = TLoggerUtil.getLogger(ShowHtmlAiResponse.class);
	
	public static final String NAME = "show_html_content";
	public static final String DESCRIPTION = """
		    This function is responsible for displaying HTML content generated by the AI directly in the system interface.

		    Purpose:
		    - Render dynamic HTML fragments created by the AI to provide visually organized responses.

		    Usage Context:
		    - Call this function when the response requires formatting (tables, lists, cards, diagrams) better suited for HTML than plain text.
		    - The target view 'Teros AI Response' acts as a direct HTML renderer.

		    CRITICAL OUTPUT RULES (Follow Strictly):
		    1. **RAW HTML ONLY**: You must return a raw HTML string.
		    2. **NO ESCAPING**: Do NOT escape HTML tags. For example, return "<div>" (CORRECT), never "&lt;div&gt;" (WRONG).
		    3. **NO MARKDOWN**: Do NOT wrap the output in Markdown code blocks (e.g., ```html ... ```). Do NOT use backticks.
		    4. **NO DOCUMENT TAGS**: Do NOT include <html>, <head>, <body>, or <script>.
		    5. **MERMAID DIAGRAMS**: To insert diagrams, use exactly: <div class="mermaid">...syntax...</div>.

		    Content Guidelines:
		    - Use standard HTML5 tags (div, h3, p, ul, table, strong, span).
		    - Use inline CSS for styling to ensure it looks good on a dark background.
		    - Ensure the content is safe for insertion via 'innerHTML'.

		    Example of CORRECT call:
		    show_html_content(htmlContent="<div style='padding:10px;'><h3>Title</h3><p>Content here.</p></div>")

		    Example of WRONG call (Do NOT do this):
		    show_html_content(htmlContent="```html\n&lt;div&gt;...&lt;/div&gt;\n```")
		    """;
	
	public ShowHtmlAiResponse() {
		super(NAME, DESCRIPTION, HtmlContent.class, 
				v->{
					LOGGER.info("Html content received: {}",v.htmlContent());
					return run(v); 
				});
		setRevertToTheAIModelInCaseOfSuccess(false);
	}

	@SuppressWarnings({ "rawtypes", "unchecked" })
	private static ToolCallResult run(HtmlContent v) {
		TedrosAppManager manager = TedrosAppManager.getInstance();
		
		ITView<TDynaPresenter> vw = manager.getCurrentView();
		
		if(vw==null || vw.gettPresenter().getModelViewClass()!=HtmlMessageViewerMV.class) {
			
			TViewDescriptor vd = manager.getViewDescriptor(HtmlMessageViewerMV.class, HtmlMessageViewerModel.class);
			
			ViewPath path = new ViewPath();
			path.setViewPath(vd.getPath());
			
			LOGGER.info("Trying to open the view: {}", path.getViewPath());
			
			manager.listenView(c-> run(v), path.getViewPath());
			
			TFunctionHelper.callUpViewFunction().getCallback().apply(path);
			
			return ToolCallResult.builder()
					.message("HTML content rendered successfully.")
					.result(Map.of(
		                    STATUS, SUCCESS,
		                    ACTION, "html_rendered",
		                    SYSTEM_INSTRUCTION, "### Html content rendered successfully. \n"
		                    		+ "VERY IMPORTANT: Do not retry again. Inform the user to check the opened view."
		                ))
					.build();
		} else {
		
			TDynaPresenter p = vw.gettPresenter();
			 
			Platform.runLater(()->{						
				
				ITModelForm form = ((TViewBehavior) p.getBehavior()).getForm();
				
				TerosWebViewBridge webViewBridge = form.gettObjectRepository().get("webviewbridge");
				
				if(webViewBridge==null) {							
					ITFieldBox fdbox = form.gettFieldBox("webContent");
					WebView wv = (WebView) fdbox.gettControl();
					webViewBridge = new TerosWebViewBridge(wv);
					form.gettObjectRepository().add("webviewbridge", webViewBridge);
				}
				
				webViewBridge.run(v.htmlContent());
				
			});
			
			return ToolCallResult.builder()
					.message("HTML content rendered successfully.")
					.result(Map.of(
		                    STATUS, SUCCESS,
		                    ACTION, "html_rendered",
		                    SYSTEM_INSTRUCTION, "### Html content rendered successfully. \n"
		                    		+ "VERY IMPORTANT: Do not retry again. Inform the user to check the opened view."
		                ))
					.build();
		}
	}	

}